<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="sakshi" ignored="0" name="Test" tests="3" failures="2" timestamp="04 Mar 2021 16:56:10 GMT" time="40.838" errors="0">
  <testcase name="loginMercury" time="12.987" classname="com.sanyam.testproject.TestDemo"/>
  <testcase name="testCase2" time="1.308" classname="com.sanyam.testproject.TestDemo">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	Test Fail 2-C:\Java_Selenium_Items\My_Workspace\Repo_TestNGProjectWithJava\TestNGProjectWithJava\ScreenShot\Fail2_Thu_Mar_04_22_26_08_IST_2021.png,
	Test Fail 3">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
Test Fail 2-C:\Java_Selenium_Items\My_Workspace\Repo_TestNGProjectWithJava\TestNGProjectWithJava\ScreenShot\Fail2_Thu_Mar_04_22_26_08_IST_2021.png,
Test Fail 3
at com.sanyam.testproject.TestDemo.testCase2(TestDemo.java:73)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- testCase2 -->
  <testcase name="testCase2" time="1.314" classname="com.sanyam.testproject.TestDemo">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at com.sanyam.frameworkpackage.ExtentManager.getScreenshot(ExtentManager.java:48)
at com.sanyam.frameworkpackage.TestListners.onTestFailure(TestListners.java:82)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- testCase2 -->
</testsuite> <!-- Test -->
