<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="1" failed="1" ignored="0" total="4" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Suite1" duration-ms="34700" started-at="2020-08-05T15:43:37Z" finished-at="2020-08-05T15:44:11Z">
    <groups>
    </groups>
    <test name="Regression1" duration-ms="34700" started-at="2020-08-05T15:43:37Z" finished-at="2020-08-05T15:44:11Z">
      <class name="com.sanyam.SeleniumProject.TestDemo">
        <test-method status="PASS" signature="initAll()[pri:0, instance:com.sanyam.SeleniumProject.TestDemo@1817d444]" name="initAll" is-config="true" duration-ms="338" started-at="2020-08-05T15:43:37Z" finished-at="2020-08-05T15:43:37Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initAll -->
        <test-method status="PASS" signature="openBrowserUrl()[pri:0, instance:com.sanyam.SeleniumProject.TestDemo@1817d444]" name="openBrowserUrl" is-config="true" duration-ms="23928" started-at="2020-08-05T15:43:37Z" finished-at="2020-08-05T15:44:01Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openBrowserUrl -->
        <test-method status="PASS" signature="loginMercury()[pri:0, instance:com.sanyam.SeleniumProject.TestDemo@1817d444]" name="loginMercury" duration-ms="9280" started-at="2020-08-05T15:44:01Z" finished-at="2020-08-05T15:44:10Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginMercury -->
        <test-method status="FAIL" signature="testCase2()[pri:0, instance:com.sanyam.SeleniumProject.TestDemo@1817d444]" name="testCase2" duration-ms="900" started-at="2020-08-05T15:44:10Z" finished-at="2020-08-05T15:44:11Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
Test Fail 2-C:\Users\$akshi\workspace\TestNGProjectWithJava\ScreenShot\Fail2_Wed_Aug_05_21_14_11_IST_2020.png,
Test Fail 3]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
Test Fail 2-C:\Users\$akshi\workspace\TestNGProjectWithJava\ScreenShot\Fail2_Wed_Aug_05_21_14_11_IST_2020.png,
Test Fail 3
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at com.sanyam.SeleniumProject.TestDemo.testCase2(TestDemo.java:82)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCase2 -->
        <test-method status="SKIP" signature="testSkip()[pri:0, instance:com.sanyam.SeleniumProject.TestDemo@1817d444]" name="testSkip" duration-ms="1" started-at="2020-08-05T15:44:11Z" finished-at="2020-08-05T15:44:11Z">
          <exception class="org.testng.SkipException">
            <message>
              <![CDATA[Testig Skip test]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.SkipException: Testig Skip test
at com.sanyam.SeleniumProject.TestDemo.testSkip(TestDemo.java:100)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.SkipException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testSkip -->
        <test-method status="PASS" signature="testSuccess()[pri:0, instance:com.sanyam.SeleniumProject.TestDemo@1817d444]" name="testSuccess" duration-ms="2" started-at="2020-08-05T15:44:11Z" finished-at="2020-08-05T15:44:11Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testSuccess -->
        <test-method status="PASS" signature="aftertest()[pri:0, instance:com.sanyam.SeleniumProject.TestDemo@1817d444]" name="aftertest" is-config="true" duration-ms="0" started-at="2020-08-05T15:44:11Z" finished-at="2020-08-05T15:44:11Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- aftertest -->
      </class> <!-- com.sanyam.SeleniumProject.TestDemo -->
    </test> <!-- Regression1 -->
  </suite> <!-- Suite1 -->
</testng-results>
