<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="1" failed="2" ignored="0" total="7" passed="4">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="53637" started-at="2021-03-28T23:01:34Z" finished-at="2021-03-28T23:02:28Z">
    <groups>
    </groups>
    <test name="Test2" duration-ms="52521" started-at="2021-03-28T23:01:34Z" finished-at="2021-03-28T23:02:27Z">
      <class name="com.sanyam.testproject.HomePageTest">
        <test-method status="PASS" signature="Setup(org.testng.ITestContext)[pri:0, instance:com.sanyam.testproject.HomePageTest@67b467e9]" name="Setup" is-config="true" duration-ms="41877" started-at="2021-03-29T04:31:34Z" finished-at="2021-03-29T04:32:16Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[org.testng.TestRunner@6d3af739]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Setup -->
        <test-method status="PASS" signature="veriftLoggedInUSerTest()[pri:0, instance:com.sanyam.testproject.HomePageTest@67b467e9]" name="veriftLoggedInUSerTest" duration-ms="3600" started-at="2021-03-29T04:32:16Z" finished-at="2021-03-29T04:32:20Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- veriftLoggedInUSerTest -->
        <test-method status="PASS" signature="contactsButtonTest()[pri:1, instance:com.sanyam.testproject.HomePageTest@67b467e9]" name="contactsButtonTest" duration-ms="3338" started-at="2021-03-29T04:32:20Z" finished-at="2021-03-29T04:32:23Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- contactsButtonTest -->
        <test-method status="PASS" signature="teardown()[pri:0, instance:com.sanyam.testproject.HomePageTest@67b467e9]" name="teardown" is-config="true" duration-ms="3617" started-at="2021-03-29T04:32:23Z" finished-at="2021-03-29T04:32:27Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- com.sanyam.testproject.HomePageTest -->
    </test> <!-- Test2 -->
    <test name="Test1" duration-ms="53637" started-at="2021-03-28T23:01:34Z" finished-at="2021-03-28T23:02:28Z">
      <class name="com.sanyam.testproject.LoginPageTest">
        <test-method status="PASS" signature="setUp(org.testng.ITestContext)[pri:0, instance:com.sanyam.testproject.LoginPageTest@289d1c02]" name="setUp" is-config="true" duration-ms="37471" started-at="2021-03-29T04:31:34Z" finished-at="2021-03-29T04:32:12Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[org.testng.TestRunner@7e9a5fbe]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="loginFreeCRM()[pri:0, instance:com.sanyam.testproject.LoginPageTest@289d1c02]" name="loginFreeCRM" duration-ms="4380" started-at="2021-03-29T04:32:12Z" finished-at="2021-03-29T04:32:16Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginFreeCRM -->
        <test-method status="PASS" signature="testSuccess()[pri:1, instance:com.sanyam.testproject.LoginPageTest@289d1c02]" name="testSuccess" duration-ms="2" started-at="2021-03-29T04:32:16Z" finished-at="2021-03-29T04:32:16Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testSuccess -->
        <test-method status="FAIL" signature="testCase2()[pri:2, instance:com.sanyam.testproject.LoginPageTest@289d1c02]" name="testCase2" duration-ms="5774" started-at="2021-03-29T04:32:16Z" finished-at="2021-03-29T04:32:22Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
	Test Fail 1-C:\Java_Selenium_Items\My_Workspace\Repo_TestNGProjectWithJava\TestNGProjectWithJava\ScreenShot\Fail2_Mon_Mar_29_04_32_17_IST_2021.png,
	Test Fail 2]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
	Test Fail 1-C:\Java_Selenium_Items\My_Workspace\Repo_TestNGProjectWithJava\TestNGProjectWithJava\ScreenShot\Fail2_Mon_Mar_29_04_32_17_IST_2021.png,
	Test Fail 2
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at com.sanyam.testproject.LoginPageTest.testCase2(LoginPageTest.java:73)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:414)
	at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCase2 -->
        <test-method status="FAIL" signature="testCase3()[pri:3, instance:com.sanyam.testproject.LoginPageTest@289d1c02]" name="testCase3" duration-ms="8" started-at="2021-03-29T04:32:23Z" finished-at="2021-03-29T04:32:23Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Failed to check Failure Scenario]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Failed to check Failure Scenario
	at org.testng.Assert.fail(Assert.java:93)
	at com.sanyam.testproject.LoginPageTest.testCase3(LoginPageTest.java:79)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:414)
	at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCase3 -->
        <test-method status="SKIP" signature="testSkip()[pri:4, instance:com.sanyam.testproject.LoginPageTest@289d1c02]" name="testSkip" duration-ms="7" started-at="2021-03-29T04:32:24Z" finished-at="2021-03-29T04:32:24Z">
          <exception class="org.testng.SkipException">
            <message>
              <![CDATA[Testig Skip test]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.SkipException: Testig Skip test
	at com.sanyam.testproject.LoginPageTest.testSkip(LoginPageTest.java:85)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:414)
	at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.SkipException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testSkip -->
        <test-method status="PASS" signature="teardown()[pri:0, instance:com.sanyam.testproject.LoginPageTest@289d1c02]" name="teardown" is-config="true" duration-ms="4083" started-at="2021-03-29T04:32:24Z" finished-at="2021-03-29T04:32:28Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- com.sanyam.testproject.LoginPageTest -->
    </test> <!-- Test1 -->
  </suite> <!-- Suite -->
</testng-results>
